export const DEMONYMS: Record<string, { name: string; nameEs: string }> = {
    "Afghanistan": { name: "Afghan", nameEs: "Afgano" },
    "Albania": { name: "Albanian", nameEs: "Albanés" },
    "Algeria": { name: "Algerian", nameEs: "Argelino" },
    "Andorra": { name: "Andorran", nameEs: "Andorrano" },
    "Angola": { name: "Angolan", nameEs: "Angoleño" },
    "Antigua And Barbuda": { name: "Antiguan", nameEs: "Antiguano" },
    "Argentina": { name: "Argentine", nameEs: "Argentino" },
    "Armenia": { name: "Armenian", nameEs: "Armenio" },
    "Australia": { name: "Australian", nameEs: "Australiano" },
    "Austria": { name: "Austrian", nameEs: "Austríaco" },
    "Azerbaijan": { name: "Azerbaijani", nameEs: "Azerbaiyano" },
    "Bahamas The": { name: "Bahamian", nameEs: "Bahameño" },
    "Bahrain": { name: "Bahraini", nameEs: "Bareiní" },
    "Bangladesh": { name: "Bangladeshi", nameEs: "Bangladesí" },
    "Barbados": { name: "Barbadian", nameEs: "Barbadense" },
    "Belarus": { name: "Belarusian", nameEs: "Bielorruso" },
    "Belgium": { name: "Belgian", nameEs: "Belga" },
    "Belize": { name: "Belizean", nameEs: "Beliceño" },
    "Benin": { name: "Beninese", nameEs: "Beninés" },
    "Bhutan": { name: "Bhutanese", nameEs: "Butanés" },
    "Bolivia": { name: "Bolivian", nameEs: "Boliviano" },
    "Bosnia and Herzegovina": { name: "Bosnian", nameEs: "Bosnio" },
    "Botswana": { name: "Botswanan", nameEs: "Botsuano" },
    "Brazil": { name: "Brazilian", nameEs: "Brasileño" },
    "Brunei": { name: "Bruneian", nameEs: "Brunellense" },
    "Bulgaria": { name: "Bulgarian", nameEs: "Búlgaro" },
    "Burkina Faso": { name: "Burkinabé", nameEs: "Burkinés" },
    "Burundi": { name: "Burundian", nameEs: "Burundés" },
    "Cabo Verde": { name: "Cape Verdean", nameEs: "Caboverdiano" },
    "Cambodia": { name: "Cambodian", nameEs: "Camboyano" },
    "Cameroon": { name: "Cameroonian", nameEs: "Camerunés" },
    "Canada": { name: "Canadian", nameEs: "Canadiense" },
    "Central African Republic": { name: "Central African", nameEs: "Centroafricano" },
    "Chad": { name: "Chadian", nameEs: "Chadiano" },
    "Chile": { name: "Chilean", nameEs: "Chileno" },
    "China": { name: "Chinese", nameEs: "Chino" },
    "Colombia": { name: "Colombian", nameEs: "Colombiano" },
    "Comoros": { name: "Comoran", nameEs: "Comorense" },
    "Costa Rica": { name: "Costa Rican", nameEs: "Costarricense" },
    "Croatia (Hrvatska)": { name: "Croatian", nameEs: "Croata" },
    "Cuba": { name: "Cuban", nameEs: "Cubano" },
    "Cyprus": { name: "Cypriot", nameEs: "Chipriota" },
    "Czech Republic": { name: "Czech", nameEs: "Checo" },
    "Denmark": { name: "Danish", nameEs: "Danés" },
    "Djibouti": { name: "Djiboutian", nameEs: "Yibutiano" },
    "Dominica": { name: "Dominican", nameEs: "Dominiqués" },
    "Dominican Republic": { name: "Dominican", nameEs: "Dominicano" },
    "East Timor": { name: "East Timorese", nameEs: "Timorense" },
    "Ecuador": { name: "Ecuadorian", nameEs: "Ecuatoriano" },
    "Egypt": { name: "Egyptian", nameEs: "Egipcio" },
    "El Salvador": { name: "Salvadoran", nameEs: "Salvadoreño" },
    "Equatorial Guinea": { name: "Equatorial Guinean", nameEs: "Ecuatoguineano" },
    "Eritrea": { name: "Eritrean", nameEs: "Eritreo" },
    "Estonia": { name: "Estonian", nameEs: "Estonio" },
    "Ethiopia": { name: "Ethiopian", nameEs: "Etíope" },
    "Fiji": { name: "Fijian", nameEs: "Fiyiano" },
    "Finland": { name: "Finnish", nameEs: "Finlandés" },
    "France": { name: "French", nameEs: "Francés" },
    "Gabon": { name: "Gabonese", nameEs: "Gabonés" },
    "Gambia": { name: "Gambian", nameEs: "Gambiano" },
    "Georgia": { name: "Georgian", nameEs: "Georgiano" },
    "Germany": { name: "German", nameEs: "Alemán" },
    "Ghana": { name: "Ghanaian", nameEs: "Ghanés" },
    "Greece": { name: "Greek", nameEs: "Griego" },
    "Grenada": { name: "Grenadian", nameEs: "Granadino" },
    "Guatemala": { name: "Guatemalan", nameEs: "Guatemalteco" },
    "Guinea": { name: "Guinean", nameEs: "Guineano" },
    "Guinea-Bissau": { name: "Guinea-Bissau National", nameEs: "Bissaugambiano" },
    "Guyana": { name: "Guyanese", nameEs: "Guyanés" },
    "Haiti": { name: "Haitian", nameEs: "Haitiano" },
    "Honduras": { name: "Honduran", nameEs: "Hondureño" },
    "Hungary": { name: "Hungarian", nameEs: "Húngaro" },
    "Iceland": { name: "Icelander", nameEs: "Islandés" },
    "India": { name: "Indian", nameEs: "Indio" },
    "Indonesia": { name: "Indonesian", nameEs: "Indonesio" },
    "Iran": { name: "Iranian", nameEs: "Iraní" },
    "Iraq": { name: "Iraqi", nameEs: "Iraquí" },
    "Ireland": { name: "Irish", nameEs: "Irlandés" },
    "Israel": { name: "Israeli", nameEs: "Israelí" },
    "Italy": { name: "Italian", nameEs: "Italiano" },
    "Cote D'Ivoire (Ivory Coast)": { name: "Ivorian", nameEs: "Marfileño" },
    "Jamaica": { name: "Jamaican", nameEs: "Jamaicano" },
    "Japan": { name: "Japanese", nameEs: "Japonés" },
    "Jordan": { name: "Jordanian", nameEs: "Jordano" },
    "Kazakhstan": { name: "Kazakhstani", nameEs: "Kazajo" },
    "Kenya": { name: "Kenyan", nameEs: "Keniano" },
    "Kiribati": { name: "Kiribati", nameEs: "Kiribatiano" },
    "Kuwait": { name: "Kuwaiti", nameEs: "Kuwaití" },
    "Kyrgyzstan": { name: "Kyrgyzstani", nameEs: "Kirguís" },
    "Laos": { name: "Lao", nameEs: "Laosiano" },
    "Latvia": { name: "Latvian", nameEs: "Letón" },
    "Lebanon": { name: "Lebanese", nameEs: "Libanés" },
    "Lesotho": { name: "Basotho", nameEs: "Lesotense" },
    "Liberia": { name: "Liberian", nameEs: "Liberiano" },
    "Libya": { name: "Libyan", nameEs: "Libio" },
    "Liechtenstein": { name: "Liechtensteiner", nameEs: "Liechtensteiniano" },
    "Lithuania": { name: "Lithuanian", nameEs: "Lituano" },
    "Luxembourg": { name: "Luxembourger", nameEs: "Luxemburgués" },
    "Madagascar": { name: "Malagasy", nameEs: "Malgache" },
    "Malawi": { name: "Malawian", nameEs: "Malauí" },
    "Malaysia": { name: "Malaysian", nameEs: "Malasio" },
    "Maldives": { name: "Maldivian", nameEs: "Maldivo" },
    "Mali": { name: "Malian", nameEs: "Maliense" },
    "Malta": { name: "Maltese", nameEs: "Maltés" },
    "Mauritania": { name: "Mauritanian", nameEs: "Mauritano" },
    "Mauritius": { name: "Mauritian", nameEs: "Mauricio" },
    "Mexico": { name: "Mexican", nameEs: "Mexicano" },
    "Micronesia": { name: "Micronesian", nameEs: "Micronesio" },
    "Moldova": { name: "Moldovan", nameEs: "Moldavo" },
    "Monaco": { name: "Monegasque", nameEs: "Monegasco" },
    "Mongolia": { name: "Mongolian", nameEs: "Mongol" },
    "Montenegro": { name: "Montenegrin", nameEs: "Montenegrino" },
    "Morocco": { name: "Moroccan", nameEs: "Marroquí" },
    "Mozambique": { name: "Mozambican", nameEs: "Mozambiqueño" },
    "Namibia": { name: "Namibian", nameEs: "Namibio" },
    "Nauru": { name: "Nauruan", nameEs: "Nauruano" },
    "Nepal": { name: "Nepali", nameEs: "Nepalí" },
    "Netherlands The": { name: "Dutch", nameEs: "Neerlandés" },
    "New Zealand": { name: "New Zealander", nameEs: "Neozelandés" },
    "Nicaragua": { name: "Nicaraguan", nameEs: "Nicaragüense" },
    "Niger": { name: "Nigerien", nameEs: "Nigerino" },
    "Nigeria": { name: "Nigerian", nameEs: "Nigeriano" },
    "North Korea": { name: "North Korean", nameEs: "Norcoreano" },
    "Macedonia": { name: "Macedonian", nameEs: "Macedonio" },
    "Norway": { name: "Norwegian", nameEs: "Noruego" },
    "Oman": { name: "Omani", nameEs: "Omaní" },
    "Pakistan": { name: "Pakistani", nameEs: "Pakistaní" },
    "Palau": { name: "Palauan", nameEs: "Palauano" },
    "Palestinian Territory, Occupied": { name: "Palestinian", nameEs: "Palestino" },
    "Panama": { name: "Panamanian", nameEs: "Panameño" },
    "Papua New Guinea": { name: "Papua New Guinean", nameEs: "Papú" },
    "Paraguay": { name: "Paraguayan", nameEs: "Paraguayo" },
    "Peru": { name: "Peruvian", nameEs: "Peruano" },
    "Philippines": { name: "Filipino", nameEs: "Filipino" },
    "Poland": { name: "Polish", nameEs: "Polaco" },
    "Portugal": { name: "Portuguese", nameEs: "Portugués" },
    "Qatar": { name: "Qatari", nameEs: "Qatarí" },
    "Romania": { name: "Romanian", nameEs: "Rumano" },
    "Russia": { name: "Russian", nameEs: "Ruso" },
    "Rwanda": { name: "Rwandan", nameEs: "Ruandés" },
    "Saint Kitts And Nevis": { name: "Kittitian", nameEs: "Sancristobaleño" },
    "Saint Lucia": { name: "Saint Lucian", nameEs: "Santaluceño" },
    "Saint Vincent And The Grenadines": { name: "Saint Vincentian", nameEs: "Sanvicentino" },
    "Samoa": { name: "Samoan", nameEs: "Samoano" },
    "San Marino": { name: "Sammarinese", nameEs: "Sanmarinense" },
    "Sao Tome and Principe": { name: "Sao Tomean", nameEs: "Santotomense" },
    "Saudi Arabia": { name: "Saudi Arabian", nameEs: "Saudí" },
    "Senegal": { name: "Senegalese", nameEs: "Senegalés" },
    "Serbia": { name: "Serbian", nameEs: "Serbio" },
    "Seychelles": { name: "Seychellois", nameEs: "Seychellense" },
    "Sierra Leone": { name: "Sierra Leonean", nameEs: "Sierraleonés" },
    "Singapore": { name: "Singaporean", nameEs: "Singapurense" },
    "Slovakia": { name: "Slovak", nameEs: "Eslovaco" },
    "Slovenia": { name: "Slovenian", nameEs: "Esloveno" },
    "Solomon Islands": { name: "Solomon Islander", nameEs: "Salomonense" },
    "Somalia": { name: "Somali", nameEs: "Somalí" },
    "South Africa": { name: "South African", nameEs: "Sudafricano" },
    "South Korea": { name: "South Korean", nameEs: "Surcoreano" },
    "South Sudan": { name: "South Sudanese", nameEs: "Sursudanés" },
    "Spain": { name: "Spanish", nameEs: "Español" },
    "Sri Lanka": { name: "Sri Lankan", nameEs: "Ceilandés" },
    "Sudan": { name: "Sudanese", nameEs: "Sudanés" },
    "Suriname": { name: "Surinamese", nameEs: "Surinamés" },
    "Sweden": { name: "Swedish", nameEs: "Sueco" },
    "Switzerland": { name: "Swiss", nameEs: "Suizo" },
    "Syria": { name: "Syrian", nameEs: "Sirio" },
    "Taiwan": { name: "Taiwanese", nameEs: "Taiwanés" },
    "Tajikistan": { name: "Tajikistani", nameEs: "Tayiko" },
    "Tanzania": { name: "Tanzanian", nameEs: "Tanzano" },
    "Thailand": { name: "Thai", nameEs: "Tailandés" },
    "Togo": { name: "Togolese", nameEs: "Togolés" },
    "Tonga": { name: "Tongan", nameEs: "Tongano" },
    "Trinidad And Tobago": { name: "Trinidadian", nameEs: "Trinitense" },
    "Tunisia": { name: "Tunisian", nameEs: "Tunecino" },
    "Turkey": { name: "Turkish", nameEs: "Turco" },
    "Turkmenistan": { name: "Turkmen", nameEs: "Turcomano" },
    "Tuvalu": { name: "Tuvaluan", nameEs: "Tuvaluano" },
    "Uganda": { name: "Ugandan", nameEs: "Ugandés" },
    "Ukraine": { name: "Ukrainian", nameEs: "Ucraniano" },
    "United Arab Emirates": { name: "Emirati", nameEs: "Emiratí" },
    "United Kingdom": { name: "British", nameEs: "Británico" },
    "United States": { name: "American", nameEs: "Estadounidense" },
    "Uruguay": { name: "Uruguayan", nameEs: "Uruguayo" },
    "Uzbekistan": { name: "Uzbekistani", nameEs: "Uzbeko" },
    "Vanuatu": { name: "Vanuatuan", nameEs: "Vanuatuense" },
    "Vatican City State (Holy See)": { name: "Vatican", nameEs: "Vaticano" },
    "Venezuela": { name: "Venezuelan", nameEs: "Venezolano" },
    "Vietnam": { name: "Vietnamese", nameEs: "Vietnamita" },
    "Yemen": { name: "Yemeni", nameEs: "Yemení" },
    "Zambia": { name: "Zambian", nameEs: "Zambiano" },
    "Zimbabwe": { name: "Zimbabwean", nameEs: "Zimbabuense" }
};
